version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # command: npm start
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ssl:/app/ssl:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge